### ISSUE TITLE
LDAPS

### ISSUE THREAD

**Issue by jonny190** [tiredofit/docker-self-service-password#14]
How can this be used with LDAPS i can't see a way of adding the CA

**Comment by el3ctrician** [comment]
same issue here ! +1

**Comment by posteingang** [comment]
I created a workaround for me in Kubernetes. Maybe it helps:

configmap.yaml
```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: self-service-password-ldap
  namespace: default
data:
  ldap.conf: |
    TLS_REQCERT allow
```

deployment.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sspw-wads-self-service-password
  namespace: "default"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: self-service-password
        app.kubernetes.io/instance: sspw
    spec:
      volumes:
      - name: ldap-conf
        configMap:
          name: sspw-wads-self-service-password-ldap
      containers:
        - name: self-service-password
          volumeMounts:
          - mountPath: /etc/openldap
            name: ldap-conf
          image: "tiredofit/self-service-password:5.0.2"
[ ... ]
```
