### ISSUE TITLE
Environment variable configs with spaces get truncated by sed

### ISSUE THREAD

**Issue by Angelin01** [tiredofit/docker-self-service-password#34]
I have been trying to set the "MAIL_FROM_NAME" variable for a bit now, however I can't for the life of me work around the sed's replacements. With the signature, where I wanted new lines, I used a block and escaped the backslashes once for the sed and that is that. Docker compose snippet:
```yml
environment:
  MAIL_USE_LDAP: 'true'
  MAIL_FROM_NAME: >-
    Password Service
  MAIL_SIGNATURE: >-
    \\n\\n--\\n\\n
  NOTIFY_ON_CHANGE: 'true'
```
The end result is always similar to `$mail_from_name = "Password";`.
I have tried using `Password\ Service`, however that leads to no change. With `Password\\ Service` I get `$mail_from_name = "Password\";`. Adding further slashes just increases the amount of slashes on the output every other slash, it doesn't actually escape the space character.

Any help would be appreciated, I'd prefer to configure the entire thing through the environment variables instead of manually as it makes it easier to also configure sensitive variables like the email password.
