### ISSUE TITLE
Missing base path parameter when using ingress controller in kubernetes

### ISSUE THREAD

**Issue by rbr101** [tiredofit/docker-self-service-password#40]
Hi all,

There should be a BASE_PATH parameter when using ingress controller/kubernetes. Now i specify ingress on path /ssp and only the index.php is shown. Links to css and images are broken. There is an option IS_BEHIND_PROXY and SITE_URL but that does not work for the ingress(reverse proxy)

I configured ingress for multiple apps like phpmyadmin/phpldapadmin/bookstack etc and there it works fine after specifying the base_path. This settings however is missing from SSP, or i haven't found it.

**Comment by rbr101** [comment]
I have fixed it, was a wrong setting in the ingress.yaml.
Use:
```
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: https-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    ingress.kubernetes.io/add-base-url: "true"
spec:
  rules:
  - http:
      paths:
        - path: /ssp
          pathType: Prefix
          backend:
            serviceName: ssp
            servicePort: 80
```
