### ISSUE TITLE
"/etc/nginx/nginx.conf.d/php-fpm.conf" failed (2: No such file or directory) (after upgrading to 5.2.2)

### ISSUE THREAD

**Issue by Montg0mery** [tiredofit/docker-self-service-password#55]
### Summary

After upgrading the Docker image from 5.2.1 to 5.2.2, it failed to start.

### Steps to reproduce

Upgrade from 5.2.1 to 5.2.2.

### What is the expected *correct* behavior?

Self Service Password should start up as normal.

### Relevant logs and/or screenshots

```
2022-06-26.11:07:43 [STARTING] ** [nginx] [50] Starting nginx 1.23.0
nginx: [emerg] open() "/etc/nginx/nginx.conf.d/php-fpm.conf" failed (2: No such file or directory) in /etc/nginx/sites.available/ssp.conf:11
2022-06-26.11:07:44 [ERROR] ** [nginx] POTENTIAL RUNWAY DETECTECTED: Disabling 10-nginx service because it has tried restarting '50' times
```

### Environment
From `docker-compose.yml`:
```
  passwordchange:
    container_name: passwordchange
    hostname: passwordchange
    domainname: research.coretechsec.com
#    image: tiredofit/self-service-password:latest
    image: tiredofit/self-service-password:5.2.1
    restart: unless-stopped
    expose:
      - 80
    volumes:
      - /containers/passwordchange:/www/ssp
    environment:
      - LDAP_SERVER=ldap
      - LDAP_STARTTLS=false
      - LDAP_BINDDN=cn=xxx
      - LDAP_BINDPASS=${LDAP_ADMIN_PASSWORD}
      - LDAP_BASE_SEARCH=xxx
      - LDAP_FILTER
      - LDAP_ANSWER_ATTRIBUTE=info
      - LDAP_LOGIN_ATTRIBUTE=uid
      - LDAP_FULLNAME_ATTRIBUTE=cn
      - LDAP_MAIL_ATTRIBUTE=mail
      - LDAP_SMS_ATTRIBUTE==nobile
      - LDAP_SSHKEY_ATTRIBUTE=sshPublicKey
      - AD_OPT_CHANGE_EXPIRED_PASSWORD=true
      - AD_OPT_FORCE_PWD_CHANGE=false
      - AD_OPT_FORCE_UNLOCK=false
      - ADMODE=false
      - PASSWORD_HASH=SSHA
      - QUESTIONS_ANSWER_OBJECTCLASS=extensibleObject
      - SAMBA_EXPIRE_DAYS=0
      - SAMBA_MAX_AGE=0
      - SAMBA_MIN_AGE=0
      - SAMBA_MODE=true
      - SHADOW_OPT_UPDATE_SHADOWEXPIRE=false
      - SHADOW_OPT_UPDATE_SHADOWLASTCHANGE=false
      - PASSWORD_DIFFERENT_LOGIN=true
      - PASSWORD_MAX_LENGTH=0
      - PASSWORD_MIN_DIGIT=1
      - PASSWORD_MIN_LENGTH=8
      - PASSWORD_MIN_LOWERCASE=1
      - PASSWORD_MIN_SPECIAL=1
      - PASSWORD_MIN_UPPERCASE=0
      - PASSWORD_NO_REUSE=false
      - PASSWORD_NO_SPECIAL_ENDS=false
      - PASSWORD_SHOW_POLICY_POSITION=above
      - PASSWORD_SHOW_POLICY=never
      - PASSWORD_SPECIAL_CHARACTERS=^a-zA-Z0-9
      - PASSWORD_USE_PWNED=false
      - WHO_CAN_CHANGE_PASSWORD=user
      - USE_QUESTIONS=false
      - NOTIFY_ON_CHANGE=false
      - NOTIFY_ON_SSHKEY_CHANGE=false
      - USE_TOKENS=false
      - USE_SMS=false
      - USE_RECAPTCHA=false
      - DEBUG_MODE=false
      - DEFAULT_ACTION=change
      - ENABLE_RESET_LOG=false
      - IS_BEHIND_PROXY=true
      - SITE_URL=https://xxx
      - LANG=en
      - SHOW_HELP=true
    depends_on:
      - ldap
    links: 
      - ldap
    networks:
      - nginxnet
      - ldapnet
```

Downgrading back to 5.2.1 fixed the issue.
