### ISSUE TITLE
Setting (undocumented) PASSWORD_COMPLEXITY does not work

### ISSUE THREAD

**Issue by stefandesu** [tiredofit/docker-self-service-password#57]
### Summary

I was looking into how to set LDAP Tool Box Self Service Password's `$pwd_complexity` ("how many different class of characters (lower, upper, digit, special) are needed in the password") and found that [this file](https://github.com/tiredofit/docker-self-service-password/blob/master/install/assets/defaults/30-self-service-password) contains environmental variable `PASSWORD_COMPLEXITY`. This variable is not documented in the README, but I expected it to work nonetheless. However, setting it to value `3` did not enforce the use of three different classes of characters.

### Steps to reproduce

1. Set `PASSWORD_COMPLEXITY` environment variable to a value larger than 1.
2. Try setting a password which does not adhere to that restriction. Example: Use value 3 and try password "hello-world" (which has only two classes of characters).
3. The password is accepted even though it does not fulfill the policy.

### What is the expected *correct* behavior?

I would expect the new password to be rejected if it does not fulfill the policy.

### Relevant logs and/or screenshots

\-

### Environment

- Image version / tag:  latest
- Host OS: Ubuntu 20.04.4

<details>
<summary>Any logs | docker-compose.yml</summary>

```yml
version: "3"
services:

  ssp:
    image: tiredofit/self-service-password:latest
    networks:
      - traefik
    volumes:
      - ./data/ssp-logs:/www/logs
    environment:
      ## LDAP
      - LDAP_SERVER=ldap://openldap
      - LDAP_STARTTLS=false
      - LDAP_BINDDN=${LDAP_ADMIN_USER}
      - LDAP_BINDPASS=${LDAP_ADMIN_PASS}
      - LDAP_BASE_SEARCH=${LDAP_SEARCH_BASEDN}
      - LDAP_LOGIN_ATTRIBUTE=${LDAP_USERNAME_FIELD}
      - LDAP_FULLNAME_ATTRIBUTE=${LDAP_NAME_FIELD}
      - PASSWORD_HASH=CRYPT
      - PASSWORD_MIN_LENGTH=8
      - PASSWORD_COMPLEXITY=3
      - PASSWORD_NO_REUSE=true
      - PASSWORD_SHOW_POLICY=always
      - PASSWORD_SHOW_POLICY_POSITION=below
      - WHO_CAN_CHANGE_PASSWORD=user
      - QUESTIONS_ENABLED=false
      - IS_BEHIND_PROXY=true
      - SHOW_HELP=true
      - LANG=en
      - SECRETEKEY=${SSP_SECRETEKEY}
      - USE_RECAPTCHA=false
      - DEFAULT_ACTION=change
      - USE_TOKENS=true
      - MAIL_USE_LDAP=true
      - LDAP_MAIL_ATTRIBUTE=mail
      - MAIL_FROM=${SMTP_FROM}
      - NOTIFY_ON_CHANGE=true
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_AUTH_ON=true
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_SECURE_TYPE=${SMTP_TYPE}
    labels:
      - traefik.enable=true
      - traefik.http.routers.ssp.rule=Host(`ssp.${DOMAIN}`)
    restart: unless-stopped

networks:
  traefik:
    external:
      name: traefik_webgateway
```

</details>

    
### Possible fixes

Maybe the variable has to be added to [this file](https://github.com/tiredofit/docker-self-service-password/blob/master/install/etc/cont-init.d/30-self-service-password) as well?
